Repository GSG-G13/workout-tracker, pull requests merged in 2023-04, with the labels that each got.

#2 file-strucutre
  .gitignore
  __tests__/test.js
  package-lock.json
  package.json
  public/app.js
  public/css/style.css
  public/index.html
  public/workout.html
  src/app.js
  src/controllers/users/addUser.js
  src/controllers/workouts/addWorkout.js
  src/controllers/workouts/getWorkouts.js
  src/controllers/workouts/index.js
  src/database/config/connection.js
  src/database/confiq.sql
  src/database/index.js
  src/database/queries/getData.js
  src/database/queries/index.js
  src/database/queries/postData.js
  src/index.js
Labels: approved

#4 ui section
  public/css/style.css
  public/css/workout.css
  public/index.html
  public/workout.html
Labels: approved

#6 create server
  src/app.js
  src/index.js
Labels: done

#10 login page and workouts html and css
  public/app.js
  public/css/style.css
  public/css/workout.css
  public/index.html
  public/js/dom.js
  public/workout.html
  src/controllers/users/addUser.js
  src/controllers/workouts/getWorkouts.js
  src/controllers/workouts/index.js
  src/controllers/workouts/postWorkout.js
  src/database/config/connection.js
  src/database/confiq.sql
  src/database/queries/addUser.js
  src/database/queries/index.js
  src/router.js
Labels: waiting-review

#13 12 fetch data
  package-lock.json
  package.json
  public/app.js
  public/css/style.css
  public/index.html
  public/js/dom.js
  public/workout.html
  src/app.js
  src/controllers/users/addUser.js
  src/controllers/workouts/getWorkouts.js
  src/controllers/workouts/index.js
  src/controllers/workouts/postWorkout.js
  src/database/config/connection.js
  src/database/confiq.sql
  src/database/index.js
  src/database/queries/addUser.js
  src/database/queries/getData.js
  src/database/queries/postData.js
  src/router.js
Labels: approved

#14 deployment
  src/database/config/connection.js
Labels: approved

#16 readme
  README.md
  src/database/queries/addUser.js
Labels: waiting-review
